# site settings
title: Pista ng Mapa 2021
description: "a free and open mapping conference in the Philippines"
email: "pistangmapa@gmail.com"
baseurl: "/2021"
logo: "/assets/img/site/WFH_Feels_full_bg.png"
favicon: favicon.ico
repo_address: "pistangmapa/2021"
messenger: ""
facebook: "PistaNgMapa2020"
twitter: "pistangmapa"
instagram: ""
mastodon: "@pistangmapa"
telegram: "pistangmapa"
github: "pistangmapa"
yt-stream-link: "https://www.youtube.com/channel/UCBK_Xl0waWLv--GpvrcTzVQ/live"

# tito event
tito-event: "pistangmapa/2021-online"


# exclude
exclude:
    - .gitignore
    - Gemfile
    - Gemfile.lock

# build settings
markdown: kramdown
highlighter: rouge
# kramdown:
#     input: GFM
#     syntax_highlighter: rouge

# plugins
plugins:
    - github-pages
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-redirect-from
